AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 7-142 Creating SAM Template - Hello World
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs8.10
    Timeout: 5
Resources:
  eventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
        FileUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: MyBucket
            Events: s3:ObjectCreated:*
      CodeUri: s3://pnj-sam/24ef64debefb706eefb8dda117162395
  MyBucket:
    Type: AWS::S3::Bucket
  addNumbers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
      Events:
        PostAdd:
          Type: Api
          Properties:
            Path: /add
            Method: post
      CodeUri: s3://pnj-sam/24ef64debefb706eefb8dda117162395
